// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BSm6ZJxHQ7XadOYPwQWFNR11C3ywHm0',
    appId: '1:774945545425:android:edf090bf1ada7ff69a39f0',
    messagingSenderId: '774945545425',
    projectId: 'todo-12e54',
    storageBucket: 'todo-12e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlR7AS-grjil9EgjooR-Jb86ZEIAzYfF8',
    appId: '1:774945545425:ios:16f731d88d3fa2469a39f0',
    messagingSenderId: '774945545425',
    projectId: 'todo-12e54',
    storageBucket: 'todo-12e54.appspot.com',
    androidClientId: '774945545425-4jtdggpprcgrokhhaom9dmlt839idhqp.apps.googleusercontent.com',
    iosClientId: '774945545425-mhv87ei38n3575pcf3of29585v15j398.apps.googleusercontent.com',
    iosBundleId: 'com.rakeshm126.todo',
  );
}
